# Generated by Django 5.1.5 on 2025-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_items_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
