# Generated by Django 5.1.6 on 2025-02-07 17:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_items_actual_price_alter_items_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
